extends RefCounted
class_name KeyRingSettings

const BARRIER_COLOR := Color(0.18, 0.21, 0.32, 1)
const RING_OUTER_MARGIN := 120.0
const MIN_RING_SPACING := 150.0
const MIN_INNER_HALF := 120.0
const WALL_THICKNESS := 52.0
const KEY_SEPARATION := 90.0
const KEY_WALL_OFFSET := 60.0
const SECOND_DOOR_PROBABILITY := 0.35
const LEVEL_SIZE_MULTIPLIER := 1.5
const EXIT_TILE_SIZE := 64.0
const MIN_EXIT_TILES := 6.0
const MIN_INNER_AREA := EXIT_TILE_SIZE * EXIT_TILE_SIZE * MIN_EXIT_TILES
const EXIT_KEY_CLEARANCE := EXIT_TILE_SIZE * 0.85
const WALL_OBSTACLE_COLOR := Color(0.24, 0.27, 0.38, 0.95)
